name: Build and deploy backend
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/eat-backend/**

concurrency: deploy-backend
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

               
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/etimo/eat-backend
          tags: type=sha,format=long
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: apps/eat-backend/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        
        
  deploy:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - uses: Etimo/etimo-kubernetes/.github/actions/deploy@main
        with:
          image: ghcr.io/etimo/eat-backend
          tag: sha-${{ github.sha }}
          namespace: activity-tracker
          cluster: staging
          name: backend
          ingress: true
          private: false
          targetPort: 3101
          memoryLimit: 512Mi
          memoryRequests: 64Mi
          env: |
            GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}
            GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}
            BACKEND_URL="https://backend-activity-tracker.k8s.etimo.se"
            FRONTEND_URL="https://web-activity-tracker.k8s.etimo.se"
            NODE_ENV="production"
          kubeconfig: ${{secrets.KUBECONFIG}}
          